# Generated by Django 3.2 on 2022-07-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ward_id', models.BigIntegerField(default=0)),
                ('family_name', models.CharField(max_length=255)),
                ('family_head_name', models.CharField(max_length=255)),
                ('member_count', models.IntegerField(default=1)),
            ],
            options={
                'unique_together': {('family_head_name', 'ward_id')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('ward_name', models.CharField(max_length=255)),
                ('ward_head', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('age', models.IntegerField(default=1)),
                ('date_of_birth', models.DateField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
